script: |

  echo "🚀 FAST DEPLOY"

  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

  nvm use 20

  cd ~/ExpenseTracker

  # Clean changes
  git reset --hard
  git clean -fd

  # Pull latest code
  git pull origin main

  # =========================
  # FRONTEND BUILD
  # =========================
  cd frontend

  npm run build

  # =========================
  # BACKEND RESTART
  # =========================
  cd ../backend

  export PATH=$PATH:/usr/local/bin

  pm2 restart backend || pm2 start app.js --name backend

  # =========================
  # NGINX START + RELOAD
  # =========================
  sudo systemctl start nginx
  sudo systemctl reload nginx

  # =========================
  # HEALTH CHECK
  # =========================
  STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost/expense/)

  echo "STATUS = $STATUS"

  if [ "$STATUS" -eq 200 ]; then
    echo "✅ WEBSITE LIVE"
  else
    echo "❌ WEBSITE DOWN"

    echo "NGINX STATUS:"
    systemctl status nginx --no-pager

    echo "PM2 STATUS:"
    pm2 list

    exit 1
  fi
