script: |

  echo "🚀 FAST DEPLOY"

  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

  cd ~/ExpenseTracker

  # IMPORTANT FIX
  git reset --hard
  git clean -fd

  git pull origin main

  export PATH=$PATH:/usr/local/bin

  pm2 restart backend || pm2 start backend/app.js --name backend

  sudo systemctl start nginx
  sudo systemctl reload nginx

  STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost/expense/)

  if [ "$STATUS" -eq 200 ]; then
    echo "✅ WEBSITE LIVE"
  else
    echo "❌ WEBSITE DOWN"
    exit 1
  fi
